# Generated by Django 6.0.3 on 2026-03-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_receita/')),
                ('ingredientes', models.TextField()),
                ('como_fazer', models.TextField()),
                ('postado_a', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
