# Generated by Django 6.0.3 on 2026-03-31 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('likes', models.ManyToManyField(related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.receita')),
            ],
        ),
    ]
